### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by itsarakio** [avseng/ai_voice_assistant#2]
hello thanks for this amazing project 
the question is ,can this project run on Raspberry Pi 3 ?
and can I buy this at this website ? https://www.amazon.com/dp/B075MBBMQ4

Please answer my question

**Comment by avseng** [comment]
Yes you can.. but it will be bit slow..

**Comment by itsarakio** [comment]
Ok and
Can I buy ReSpeaker 2-Mics Pi HAT from here ? https://www.amazon.com/dp/B075MBBMQ4
if I buy from amazon Is it compatible with Raspberry Pi 4 ?
Cuz it's version 1.0 in amazon

**Comment by theamircodex** [comment]
@avseng

**Comment by avseng** [comment]
Pi hats are all compatible with rpi3 and 4...

**Comment by itsarakio** [comment]
ok thanks for replying
